services:
  - type: web
    name: arsist
    runtime: image
    image:
      url: docker.io/arsistart/arsist:latest
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: LICENSE_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_URL_KEY
        generateValue: true
      - key: PORT
        value: 3000
    disk:
      name: arsist-data
      mountPath: /app/data
      sizeGB: 1
