services:
  - type: web
    name: arsist
    runtime: image
    image:
      url: docker.io/arsistart/arsist:latest
    plan: free
    envVars:
      - key: LICENSE_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
